# Generated by Django 3.1.2 on 2020-11-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('classification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataFromRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_in_room', models.IntegerField(default=0)),
                ('people_entered', models.IntegerField(default=0)),
                ('people_got_out', models.IntegerField(default=0)),
                ('date_published', models.DateTimeField(verbose_name='date_published')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting_people.room')),
            ],
        ),
    ]
